### ISSUE TITLE
wrong install with conda forge on the description (wslpath instead of wslPath)

### ISSUE THREAD

**Issue by arturdaraujo** [akikuno/wslPath#3]
The conda forge install is wslpath instead of wslPath

**Comment by akikuno** [comment]
Thank you for your comment.
Yes, conda-forge is case-insensitive and treats everything as lowercase. However, you can install without any issues using either `wslpath` or `wslPath`.

That said, Python imports are case-sensitive, so using `import wslpath` will result in an error. To prevent confusion where users might mistakenly write scripts using the lowercase version, we have specified `conda install -c conda-forge wslPath` in the README for clarity.

I hope this clears things up.
